// Package lifecycle provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package lifecycle

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "apiKeyAuth.Scopes"
)

// Defines values for NetworkPolicyDefaultAction.
const (
	NetworkPolicyDefaultActionAllow NetworkPolicyDefaultAction = "allow"
	NetworkPolicyDefaultActionDeny  NetworkPolicyDefaultAction = "deny"
)

// Valid indicates whether the value is a known member of the NetworkPolicyDefaultAction enum.
func (e NetworkPolicyDefaultAction) Valid() bool {
	switch e {
	case NetworkPolicyDefaultActionAllow:
		return true
	case NetworkPolicyDefaultActionDeny:
		return true
	default:
		return false
	}
}

// Defines values for NetworkRuleAction.
const (
	NetworkRuleActionAllow NetworkRuleAction = "allow"
	NetworkRuleActionDeny  NetworkRuleAction = "deny"
)

// Valid indicates whether the value is a known member of the NetworkRuleAction enum.
func (e NetworkRuleAction) Valid() bool {
	switch e {
	case NetworkRuleActionAllow:
		return true
	case NetworkRuleActionDeny:
		return true
	default:
		return false
	}
}

// Defines values for OSSFSVersion.
const (
	N10 OSSFSVersion = "1.0"
	N20 OSSFSVersion = "2.0"
)

// Valid indicates whether the value is a known member of the OSSFSVersion enum.
func (e OSSFSVersion) Valid() bool {
	switch e {
	case N10:
		return true
	case N20:
		return true
	default:
		return false
	}
}

// CreateSandboxRequest Request to create a new sandbox from a container image.
//
// **Note**: API Key authentication is required via the `OPEN-SANDBOX-API-KEY` header.
type CreateSandboxRequest struct {
	// Entrypoint The command to execute as the sandbox's entry process (required).
	//
	// Explicitly specifies the user's expected main process, allowing the sandbox management
	// service to reliably inject control processes before executing this command.
	//
	// Format: [executable, arg1, arg2, ...]
	//
	// Examples:
	// - ["python", "/app/main.py"]
	// - ["/bin/bash"]
	// - ["java", "-jar", "/app/app.jar"]
	// - ["node", "server.js"]
	Entrypoint []string `json:"entrypoint"`

	// Env Environment variables to inject into the sandbox runtime.
	Env *map[string]string `json:"env,omitempty"`

	// Extensions Opaque container for provider-specific or transient parameters not supported by the core API.
	//
	// **Note**: This field is reserved for internal features, experimental flags, or temporary behaviors. Standard parameters should be proposed as core API fields.
	//
	// **Best Practices**:
	// - **Namespacing**: Use prefixed keys (e.g., `storage.id`) to prevent collisions.
	// - **Pass-through**: SDKs and middleware must treat this object as opaque and pass it through transparently.
	//
	// **Well-known keys**:
	// - `access.renew.extend.seconds` (optional): Decimal integer string from **300** to **86400** (5 minutes to 24 hours inclusive). Opts the sandbox into OSEP-0009 renew-on-access and sets per-renewal extension seconds. Omit to disable. Invalid values are rejected at creation with HTTP 400 (validated on the lifecycle create endpoint via `validate_extensions` in server `src/extensions/validation.py`).
	Extensions *map[string]string `json:"extensions,omitempty"`

	// Image Container image specification for sandbox provisioning.
	//
	// Supports public registry images and private registry images with authentication.
	Image ImageSpec `json:"image"`

	// Metadata Custom key-value metadata for management, filtering, and tagging.
	// Use "name" key for a human-readable identifier.
	Metadata *map[string]string `json:"metadata,omitempty"`

	// NetworkPolicy Egress network policy matching the sidecar `/policy` request body.
	// If `defaultAction` is omitted, the sidecar defaults to "deny"; passing an empty
	// object or null results in allow-all behavior at startup.
	NetworkPolicy *NetworkPolicy `json:"networkPolicy,omitempty"`

	// ResourceLimits Runtime resource constraints as key-value pairs. Similar to Kubernetes resource specifications,
	// allows flexible definition of resource limits. Common resource types include:
	// - `cpu`: CPU allocation in millicores (e.g., "250m" for 0.25 CPU cores)
	// - `memory`: Memory allocation in bytes or human-readable format (e.g., "512Mi", "1Gi")
	// - `gpu`: Number of GPU devices (e.g., "1")
	//
	// New resource types can be added without API changes.
	ResourceLimits ResourceLimits `json:"resourceLimits"`

	// Timeout Sandbox timeout in seconds. The sandbox will automatically terminate after this duration.
	// The maximum is controlled by the server configuration (`server.max_sandbox_timeout_seconds`).
	// Omit this field or set it to null to disable automatic expiration and require explicit cleanup.
	// Note: manual cleanup support is runtime-dependent; Kubernetes providers may reject
	// omitted or null timeout when the underlying workload provider does not support non-expiring sandboxes.
	Timeout *int `json:"timeout,omitempty"`

	// Volumes Storage mounts for the sandbox. Each volume entry specifies a named backend-specific
	// storage source and common mount settings. Exactly one backend type must be specified
	// per volume entry.
	Volumes *[]Volume `json:"volumes,omitempty"`
}

// CreateSandboxResponse Response from creating a new sandbox. Contains essential information without image and updatedAt.
type CreateSandboxResponse struct {
	// CreatedAt Sandbox creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Entrypoint Entry process specification from creation request
	Entrypoint []string `json:"entrypoint"`

	// ExpiresAt Timestamp when sandbox will auto-terminate. Omitted when manual cleanup is enabled.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// ID Unique sandbox identifier
	ID string `json:"id"`

	// Metadata Custom metadata from creation request
	Metadata *map[string]string `json:"metadata,omitempty"`

	// Status Detailed status information with lifecycle state and transition details
	Status SandboxStatus `json:"status"`
}

// Endpoint Endpoint for accessing a service running in the sandbox.
// The service must be listening on the specified port inside the sandbox for the endpoint to be available.
type Endpoint struct {
	// Endpoint Public URL to access the service from outside the sandbox.
	// Format: {endpoint-host}/sandboxes/{sandboxId}/port/{port}
	// Example: endpoint.opensandbox.io/sandboxes/abc123/port/8080
	Endpoint string `json:"endpoint"`

	// Headers Requests targeting the sandbox must include the corresponding header(s).
	Headers *map[string]string `json:"headers,omitempty"`
}

// ErrorResponse Standard error response for all non-2xx HTTP responses.
// HTTP status code indicates the error category; code and message provide details.
type ErrorResponse struct {
	// Code Machine-readable error code (e.g., INVALID_REQUEST, NOT_FOUND, INTERNAL_ERROR).
	// Use this for programmatic error handling.
	Code string `json:"code"`

	// Message Human-readable error message describing what went wrong and how to fix it.
	Message string `json:"message"`
}

// Host Host path bind mount backend. Maps a directory on the host filesystem
// into the container. Only available when the runtime supports host mounts.
//
// Security note: Host paths are restricted by server-side allowlist.
// Users must specify paths under permitted prefixes.
type Host struct {
	// Path Absolute path on the host filesystem to mount.
	// Must start with '/' and be under an allowed prefix.
	Path string `json:"path"`
}

// ImageSpec Container image specification for sandbox provisioning.
//
// Supports public registry images and private registry images with authentication.
type ImageSpec struct {
	// Auth Registry authentication credentials (required for private registries)
	Auth *struct {
		// Password Registry password or authentication token
		Password *string `json:"password,omitempty"`

		// Username Registry username or service account
		Username *string `json:"username,omitempty"`
	} `json:"auth,omitempty"`

	// URI Container image URI in standard format.
	//
	// Examples:
	//   - "python:3.11" (Docker Hub)
	//   - "ubuntu:22.04"
	//   - "gcr.io/my-project/model-server:v1.0"
	//   - "private-registry.company.com:5000/app:latest"
	URI string `json:"uri"`
}

// ListSandboxesResponse defines model for ListSandboxesResponse.
type ListSandboxesResponse struct {
	Items []Sandbox `json:"items"`

	// Pagination Pagination metadata for list responses
	Pagination PaginationInfo `json:"pagination"`
}

// NetworkPolicy Egress network policy matching the sidecar `/policy` request body.
// If `defaultAction` is omitted, the sidecar defaults to "deny"; passing an empty
// object or null results in allow-all behavior at startup.
type NetworkPolicy struct {
	// DefaultAction Default action when no egress rule matches. Defaults to "deny".
	DefaultAction *NetworkPolicyDefaultAction `json:"defaultAction,omitempty"`

	// Egress List of egress rules evaluated in order.
	Egress *[]NetworkRule `json:"egress,omitempty"`
}

// NetworkPolicyDefaultAction Default action when no egress rule matches. Defaults to "deny".
type NetworkPolicyDefaultAction string

// NetworkRule defines model for NetworkRule.
type NetworkRule struct {
	// Action Whether to allow or deny matching targets.
	Action NetworkRuleAction `json:"action"`

	// Target FQDN or wildcard domain (e.g., "example.com", "*.example.com").
	// IP/CIDR not yet supported in the egress MVP.
	Target string `json:"target"`
}

// NetworkRuleAction Whether to allow or deny matching targets.
type NetworkRuleAction string

// OSSFS Alibaba Cloud OSS mount backend via ossfs.
//
// The runtime mounts a host-side OSS path under `storage.ossfs_mount_root`
// and bind-mounts the resolved path into the sandbox container.
// Prefix selection is expressed via `Volume.subPath`.
// In Docker runtime, OSSFS backend requires OpenSandbox Server to run on a Linux host with FUSE support.
type OSSFS struct {
	// AccessKeyID OSS access key ID for inline credentials mode.
	AccessKeyID string `json:"accessKeyId"`

	// AccessKeySecret OSS access key secret for inline credentials mode.
	AccessKeySecret string `json:"accessKeySecret"`

	// Bucket OSS bucket name.
	Bucket string `json:"bucket"`

	// Endpoint OSS endpoint (e.g., `oss-cn-hangzhou.aliyuncs.com`).
	Endpoint string `json:"endpoint"`

	// Options Additional ossfs mount options.
	// Runtime encodes options by `version`:
	// - `1.0`: mounts with `ossfs ... -o <option>`
	// - `2.0`: mounts with `ossfs2 mount ... -c <config-file>` and encodes options as `--<option>` lines in the config file
	// Option values must be provided as raw payloads without leading `-`.
	Options *[]string `json:"options,omitempty"`

	// Version ossfs major version used by runtime mount integration.
	Version *OSSFSVersion `json:"version,omitempty"`
}

// OSSFSVersion ossfs major version used by runtime mount integration.
type OSSFSVersion string

// PVC Platform-managed named volume backend. A runtime-neutral abstraction
// for referencing a pre-existing, platform-managed named volume.
//
// - Kubernetes: maps to a PersistentVolumeClaim in the same namespace.
// - Docker: maps to a Docker named volume (created via `docker volume create`).
//
// The volume must already exist on the target platform before sandbox
// creation.
type PVC struct {
	// ClaimName Name of the volume on the target platform.
	// In Kubernetes this is the PVC name; in Docker this is the named
	// volume name. Must be a valid DNS label.
	ClaimName string `json:"claimName"`
}

// PaginationInfo Pagination metadata for list responses
type PaginationInfo struct {
	// HasNextPage Whether there are more pages after the current one
	HasNextPage bool `json:"hasNextPage"`

	// Page Current page number
	Page int `json:"page"`

	// PageSize Number of items per page
	PageSize int `json:"pageSize"`

	// TotalItems Total number of items matching the filter
	TotalItems int `json:"totalItems"`

	// TotalPages Total number of pages
	TotalPages int `json:"totalPages"`
}

// RenewSandboxExpirationRequest defines model for RenewSandboxExpirationRequest.
type RenewSandboxExpirationRequest struct {
	// ExpiresAt New absolute expiration time in UTC (RFC 3339 format).
	// Must be in the future and after the current expiresAt time.
	//
	// Example: "2025-11-16T14:30:45Z"
	ExpiresAt time.Time `json:"expiresAt"`
}

// RenewSandboxExpirationResponse defines model for RenewSandboxExpirationResponse.
type RenewSandboxExpirationResponse struct {
	// ExpiresAt The new absolute expiration time in UTC (RFC 3339 format).
	//
	// Example: "2025-11-16T14:30:45Z"
	ExpiresAt time.Time `json:"expiresAt"`
}

// ResourceLimits Runtime resource constraints as key-value pairs. Similar to Kubernetes resource specifications,
// allows flexible definition of resource limits. Common resource types include:
// - `cpu`: CPU allocation in millicores (e.g., "250m" for 0.25 CPU cores)
// - `memory`: Memory allocation in bytes or human-readable format (e.g., "512Mi", "1Gi")
// - `gpu`: Number of GPU devices (e.g., "1")
//
// New resource types can be added without API changes.
type ResourceLimits map[string]string

// Sandbox Runtime execution environment provisioned from a container image
type Sandbox struct {
	// CreatedAt Sandbox creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Entrypoint The command to execute as the sandbox's entry process.
	// Always present in responses since entrypoint is required in creation requests.
	Entrypoint []string `json:"entrypoint"`

	// ExpiresAt Timestamp when sandbox will auto-terminate. Omitted when manual cleanup is enabled.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// ID Unique sandbox identifier
	ID string `json:"id"`

	// Image Container image specification for sandbox provisioning.
	//
	// Supports public registry images and private registry images with authentication.
	Image ImageSpec `json:"image"`

	// Metadata Custom metadata from creation request
	Metadata *map[string]string `json:"metadata,omitempty"`

	// Status Detailed status information with lifecycle state and transition details
	Status SandboxStatus `json:"status"`
}

// SandboxState High-level lifecycle state of the sandbox.
//
// Common state values:
// - Pending: Sandbox is being provisioned
// - Running: Sandbox is running and ready to accept requests
// - Pausing: Sandbox is in the process of pausing
// - Paused: Sandbox has been paused while retaining its state
// - Stopping: Sandbox is being terminated
// - Terminated: Sandbox has been successfully terminated
// - Failed: Sandbox encountered a critical error
//
// State transitions:
// - Pending → Running (after creation completes)
// - Running → Pausing (when pause is requested)
// - Pausing → Paused (pause operation completes)
// - Paused → Running (when resume is requested)
// - Running/Paused → Stopping (when kill is requested or TTL expires)
// - Stopping → Terminated (kill/timeout operation completes)
// - Pending/Running/Paused → Failed (on error)
//
// Note: New state values may be added in future versions.
// Clients should handle unknown state values gracefully.
type SandboxState = string

// SandboxStatus Detailed status information with lifecycle state and transition details
type SandboxStatus struct {
	// LastTransitionAt Timestamp of the last state transition
	LastTransitionAt *time.Time `json:"lastTransitionAt,omitempty"`

	// Message Human-readable message describing the current state or reason for state transition
	Message *string `json:"message,omitempty"`

	// Reason Short machine-readable reason code for the current state.
	// Examples: "user_delete", "ttl_expiry", "provision_timeout", "runtime_error"
	Reason *string `json:"reason,omitempty"`

	// State High-level lifecycle state of the sandbox.
	//
	// Common state values:
	// - Pending: Sandbox is being provisioned
	// - Running: Sandbox is running and ready to accept requests
	// - Pausing: Sandbox is in the process of pausing
	// - Paused: Sandbox has been paused while retaining its state
	// - Stopping: Sandbox is being terminated
	// - Terminated: Sandbox has been successfully terminated
	// - Failed: Sandbox encountered a critical error
	//
	// State transitions:
	// - Pending → Running (after creation completes)
	// - Running → Pausing (when pause is requested)
	// - Pausing → Paused (pause operation completes)
	// - Paused → Running (when resume is requested)
	// - Running/Paused → Stopping (when kill is requested or TTL expires)
	// - Stopping → Terminated (kill/timeout operation completes)
	// - Pending/Running/Paused → Failed (on error)
	//
	// Note: New state values may be added in future versions.
	// Clients should handle unknown state values gracefully.
	State SandboxState `json:"state"`
}

// Volume Storage mount definition for a sandbox. Each volume entry contains:
// - A unique name identifier
// - Exactly one backend struct (host, pvc, ossfs, etc.) with backend-specific fields
// - Common mount settings (mountPath, readOnly, subPath)
type Volume struct {
	// Host Host path bind mount backend. Maps a directory on the host filesystem
	// into the container. Only available when the runtime supports host mounts.
	//
	// Security note: Host paths are restricted by server-side allowlist.
	// Users must specify paths under permitted prefixes.
	Host *Host `json:"host,omitempty"`

	// MountPath Absolute path inside the container where the volume is mounted.
	// Must start with '/'.
	MountPath string `json:"mountPath"`

	// Name Unique identifier for the volume within the sandbox.
	// Must be a valid DNS label (lowercase alphanumeric, hyphens allowed, max 63 chars).
	Name string `json:"name"`

	// Ossfs Alibaba Cloud OSS mount backend via ossfs.
	//
	// The runtime mounts a host-side OSS path under `storage.ossfs_mount_root`
	// and bind-mounts the resolved path into the sandbox container.
	// Prefix selection is expressed via `Volume.subPath`.
	// In Docker runtime, OSSFS backend requires OpenSandbox Server to run on a Linux host with FUSE support.
	Ossfs *OSSFS `json:"ossfs,omitempty"`

	// Pvc Platform-managed named volume backend. A runtime-neutral abstraction
	// for referencing a pre-existing, platform-managed named volume.
	//
	// - Kubernetes: maps to a PersistentVolumeClaim in the same namespace.
	// - Docker: maps to a Docker named volume (created via `docker volume create`).
	//
	// The volume must already exist on the target platform before sandbox
	// creation.
	Pvc *PVC `json:"pvc,omitempty"`

	// ReadOnly If true, the volume is mounted as read-only. Defaults to false (read-write).
	ReadOnly *bool `json:"readOnly,omitempty"`

	// SubPath Optional subdirectory under the backend path to mount.
	// For `ossfs` backend, this field is used as the bucket prefix.
	// Must be a relative path without '..' components.
	SubPath *string `json:"subPath,omitempty"`
}

// SandboxID defines model for SandboxId.
type SandboxID = string

// BadRequest Standard error response for all non-2xx HTTP responses.
// HTTP status code indicates the error category; code and message provide details.
type BadRequest = ErrorResponse

// Conflict Standard error response for all non-2xx HTTP responses.
// HTTP status code indicates the error category; code and message provide details.
type Conflict = ErrorResponse

// Forbidden Standard error response for all non-2xx HTTP responses.
// HTTP status code indicates the error category; code and message provide details.
type Forbidden = ErrorResponse

// InternalServerError Standard error response for all non-2xx HTTP responses.
// HTTP status code indicates the error category; code and message provide details.
type InternalServerError = ErrorResponse

// NotFound Standard error response for all non-2xx HTTP responses.
// HTTP status code indicates the error category; code and message provide details.
type NotFound = ErrorResponse

// Unauthorized Standard error response for all non-2xx HTTP responses.
// HTTP status code indicates the error category; code and message provide details.
type Unauthorized = ErrorResponse

// GetSandboxesParams defines parameters for GetSandboxes.
type GetSandboxesParams struct {
	// State Filter by lifecycle state. Pass multiple times for OR logic.
	// Example: `?state=Running&state=Paused`
	State *[]string `form:"state,omitempty" json:"state,omitempty"`

	// Metadata Arbitrary metadata key-value pairs for filtering，keys and values must be url encoded
	// Example: To filter by `project=Apollo` and `note=Demo Test`: `?metadata=project%3DApollo%26note%3DDemo%252520Test`
	Metadata *string `form:"metadata,omitempty" json:"metadata,omitempty"`

	// Page Page number for pagination
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetSandboxesSandboxIDEndpointsPortParams defines parameters for GetSandboxesSandboxIDEndpointsPort.
type GetSandboxesSandboxIDEndpointsPortParams struct {
	// UseServerProxy Whether to return a server-proxied URL
	UseServerProxy *bool `form:"use_server_proxy,omitempty" json:"use_server_proxy,omitempty"`
}

// PostSandboxesJSONRequestBody defines body for PostSandboxes for application/json ContentType.
type PostSandboxesJSONRequestBody = CreateSandboxRequest

// PostSandboxesSandboxIDRenewExpirationJSONRequestBody defines body for PostSandboxesSandboxIDRenewExpiration for application/json ContentType.
type PostSandboxesSandboxIDRenewExpirationJSONRequestBody = RenewSandboxExpirationRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetSandboxes request
	GetSandboxes(ctx context.Context, params *GetSandboxesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSandboxesWithBody request with any body
	PostSandboxesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostSandboxes(ctx context.Context, body PostSandboxesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteSandboxesSandboxID request
	DeleteSandboxesSandboxID(ctx context.Context, sandboxID SandboxID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSandboxesSandboxID request
	GetSandboxesSandboxID(ctx context.Context, sandboxID SandboxID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSandboxesSandboxIDEndpointsPort request
	GetSandboxesSandboxIDEndpointsPort(ctx context.Context, sandboxID SandboxID, port int, params *GetSandboxesSandboxIDEndpointsPortParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSandboxesSandboxIDPause request
	PostSandboxesSandboxIDPause(ctx context.Context, sandboxID SandboxID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSandboxesSandboxIDRenewExpirationWithBody request with any body
	PostSandboxesSandboxIDRenewExpirationWithBody(ctx context.Context, sandboxID SandboxID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostSandboxesSandboxIDRenewExpiration(ctx context.Context, sandboxID SandboxID, body PostSandboxesSandboxIDRenewExpirationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSandboxesSandboxIDResume request
	PostSandboxesSandboxIDResume(ctx context.Context, sandboxID SandboxID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetSandboxes(ctx context.Context, params *GetSandboxesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSandboxesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSandboxesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSandboxesRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSandboxes(ctx context.Context, body PostSandboxesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSandboxesRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteSandboxesSandboxID(ctx context.Context, sandboxID SandboxID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteSandboxesSandboxIDRequest(c.Server, sandboxID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSandboxesSandboxID(ctx context.Context, sandboxID SandboxID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSandboxesSandboxIDRequest(c.Server, sandboxID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSandboxesSandboxIDEndpointsPort(ctx context.Context, sandboxID SandboxID, port int, params *GetSandboxesSandboxIDEndpointsPortParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSandboxesSandboxIDEndpointsPortRequest(c.Server, sandboxID, port, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSandboxesSandboxIDPause(ctx context.Context, sandboxID SandboxID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSandboxesSandboxIDPauseRequest(c.Server, sandboxID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSandboxesSandboxIDRenewExpirationWithBody(ctx context.Context, sandboxID SandboxID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSandboxesSandboxIDRenewExpirationRequestWithBody(c.Server, sandboxID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSandboxesSandboxIDRenewExpiration(ctx context.Context, sandboxID SandboxID, body PostSandboxesSandboxIDRenewExpirationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSandboxesSandboxIDRenewExpirationRequest(c.Server, sandboxID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSandboxesSandboxIDResume(ctx context.Context, sandboxID SandboxID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSandboxesSandboxIDResumeRequest(c.Server, sandboxID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetSandboxesRequest generates requests for GetSandboxes
func NewGetSandboxesRequest(server string, params *GetSandboxesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sandboxes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.State != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "state", *params.State, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Metadata != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "metadata", *params.Metadata, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "pageSize", *params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostSandboxesRequest calls the generic PostSandboxes builder with application/json body
func NewPostSandboxesRequest(server string, body PostSandboxesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostSandboxesRequestWithBody(server, "application/json", bodyReader)
}

// NewPostSandboxesRequestWithBody generates requests for PostSandboxes with any type of body
func NewPostSandboxesRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sandboxes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteSandboxesSandboxIDRequest generates requests for DeleteSandboxesSandboxID
func NewDeleteSandboxesSandboxIDRequest(server string, sandboxID SandboxID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "sandboxId", sandboxID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sandboxes/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSandboxesSandboxIDRequest generates requests for GetSandboxesSandboxID
func NewGetSandboxesSandboxIDRequest(server string, sandboxID SandboxID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "sandboxId", sandboxID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sandboxes/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSandboxesSandboxIDEndpointsPortRequest generates requests for GetSandboxesSandboxIDEndpointsPort
func NewGetSandboxesSandboxIDEndpointsPortRequest(server string, sandboxID SandboxID, port int, params *GetSandboxesSandboxIDEndpointsPortParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "sandboxId", sandboxID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "port", port, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sandboxes/%s/endpoints/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.UseServerProxy != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "use_server_proxy", *params.UseServerProxy, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostSandboxesSandboxIDPauseRequest generates requests for PostSandboxesSandboxIDPause
func NewPostSandboxesSandboxIDPauseRequest(server string, sandboxID SandboxID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "sandboxId", sandboxID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sandboxes/%s/pause", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostSandboxesSandboxIDRenewExpirationRequest calls the generic PostSandboxesSandboxIDRenewExpiration builder with application/json body
func NewPostSandboxesSandboxIDRenewExpirationRequest(server string, sandboxID SandboxID, body PostSandboxesSandboxIDRenewExpirationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostSandboxesSandboxIDRenewExpirationRequestWithBody(server, sandboxID, "application/json", bodyReader)
}

// NewPostSandboxesSandboxIDRenewExpirationRequestWithBody generates requests for PostSandboxesSandboxIDRenewExpiration with any type of body
func NewPostSandboxesSandboxIDRenewExpirationRequestWithBody(server string, sandboxID SandboxID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "sandboxId", sandboxID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sandboxes/%s/renew-expiration", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostSandboxesSandboxIDResumeRequest generates requests for PostSandboxesSandboxIDResume
func NewPostSandboxesSandboxIDResumeRequest(server string, sandboxID SandboxID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "sandboxId", sandboxID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sandboxes/%s/resume", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetSandboxesWithResponse request
	GetSandboxesWithResponse(ctx context.Context, params *GetSandboxesParams, reqEditors ...RequestEditorFn) (*GetSandboxesResponse, error)

	// PostSandboxesWithBodyWithResponse request with any body
	PostSandboxesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSandboxesResponse, error)

	PostSandboxesWithResponse(ctx context.Context, body PostSandboxesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSandboxesResponse, error)

	// DeleteSandboxesSandboxIDWithResponse request
	DeleteSandboxesSandboxIDWithResponse(ctx context.Context, sandboxID SandboxID, reqEditors ...RequestEditorFn) (*DeleteSandboxesSandboxIDResponse, error)

	// GetSandboxesSandboxIDWithResponse request
	GetSandboxesSandboxIDWithResponse(ctx context.Context, sandboxID SandboxID, reqEditors ...RequestEditorFn) (*GetSandboxesSandboxIDResponse, error)

	// GetSandboxesSandboxIDEndpointsPortWithResponse request
	GetSandboxesSandboxIDEndpointsPortWithResponse(ctx context.Context, sandboxID SandboxID, port int, params *GetSandboxesSandboxIDEndpointsPortParams, reqEditors ...RequestEditorFn) (*GetSandboxesSandboxIDEndpointsPortResponse, error)

	// PostSandboxesSandboxIDPauseWithResponse request
	PostSandboxesSandboxIDPauseWithResponse(ctx context.Context, sandboxID SandboxID, reqEditors ...RequestEditorFn) (*PostSandboxesSandboxIDPauseResponse, error)

	// PostSandboxesSandboxIDRenewExpirationWithBodyWithResponse request with any body
	PostSandboxesSandboxIDRenewExpirationWithBodyWithResponse(ctx context.Context, sandboxID SandboxID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSandboxesSandboxIDRenewExpirationResponse, error)

	PostSandboxesSandboxIDRenewExpirationWithResponse(ctx context.Context, sandboxID SandboxID, body PostSandboxesSandboxIDRenewExpirationJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSandboxesSandboxIDRenewExpirationResponse, error)

	// PostSandboxesSandboxIDResumeWithResponse request
	PostSandboxesSandboxIDResumeWithResponse(ctx context.Context, sandboxID SandboxID, reqEditors ...RequestEditorFn) (*PostSandboxesSandboxIDResumeResponse, error)
}

type GetSandboxesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListSandboxesResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetSandboxesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSandboxesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostSandboxesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *CreateSandboxResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON409      *Conflict
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r PostSandboxesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSandboxesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteSandboxesSandboxIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON409      *Conflict
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r DeleteSandboxesSandboxIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteSandboxesSandboxIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSandboxesSandboxIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Sandbox
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetSandboxesSandboxIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSandboxesSandboxIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSandboxesSandboxIDEndpointsPortResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Endpoint
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetSandboxesSandboxIDEndpointsPortResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSandboxesSandboxIDEndpointsPortResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostSandboxesSandboxIDPauseResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON409      *Conflict
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r PostSandboxesSandboxIDPauseResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSandboxesSandboxIDPauseResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostSandboxesSandboxIDRenewExpirationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RenewSandboxExpirationResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON409      *Conflict
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r PostSandboxesSandboxIDRenewExpirationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSandboxesSandboxIDRenewExpirationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostSandboxesSandboxIDResumeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON409      *Conflict
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r PostSandboxesSandboxIDResumeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSandboxesSandboxIDResumeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetSandboxesWithResponse request returning *GetSandboxesResponse
func (c *ClientWithResponses) GetSandboxesWithResponse(ctx context.Context, params *GetSandboxesParams, reqEditors ...RequestEditorFn) (*GetSandboxesResponse, error) {
	rsp, err := c.GetSandboxes(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSandboxesResponse(rsp)
}

// PostSandboxesWithBodyWithResponse request with arbitrary body returning *PostSandboxesResponse
func (c *ClientWithResponses) PostSandboxesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSandboxesResponse, error) {
	rsp, err := c.PostSandboxesWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSandboxesResponse(rsp)
}

func (c *ClientWithResponses) PostSandboxesWithResponse(ctx context.Context, body PostSandboxesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSandboxesResponse, error) {
	rsp, err := c.PostSandboxes(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSandboxesResponse(rsp)
}

// DeleteSandboxesSandboxIDWithResponse request returning *DeleteSandboxesSandboxIDResponse
func (c *ClientWithResponses) DeleteSandboxesSandboxIDWithResponse(ctx context.Context, sandboxID SandboxID, reqEditors ...RequestEditorFn) (*DeleteSandboxesSandboxIDResponse, error) {
	rsp, err := c.DeleteSandboxesSandboxID(ctx, sandboxID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteSandboxesSandboxIDResponse(rsp)
}

// GetSandboxesSandboxIDWithResponse request returning *GetSandboxesSandboxIDResponse
func (c *ClientWithResponses) GetSandboxesSandboxIDWithResponse(ctx context.Context, sandboxID SandboxID, reqEditors ...RequestEditorFn) (*GetSandboxesSandboxIDResponse, error) {
	rsp, err := c.GetSandboxesSandboxID(ctx, sandboxID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSandboxesSandboxIDResponse(rsp)
}

// GetSandboxesSandboxIDEndpointsPortWithResponse request returning *GetSandboxesSandboxIDEndpointsPortResponse
func (c *ClientWithResponses) GetSandboxesSandboxIDEndpointsPortWithResponse(ctx context.Context, sandboxID SandboxID, port int, params *GetSandboxesSandboxIDEndpointsPortParams, reqEditors ...RequestEditorFn) (*GetSandboxesSandboxIDEndpointsPortResponse, error) {
	rsp, err := c.GetSandboxesSandboxIDEndpointsPort(ctx, sandboxID, port, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSandboxesSandboxIDEndpointsPortResponse(rsp)
}

// PostSandboxesSandboxIDPauseWithResponse request returning *PostSandboxesSandboxIDPauseResponse
func (c *ClientWithResponses) PostSandboxesSandboxIDPauseWithResponse(ctx context.Context, sandboxID SandboxID, reqEditors ...RequestEditorFn) (*PostSandboxesSandboxIDPauseResponse, error) {
	rsp, err := c.PostSandboxesSandboxIDPause(ctx, sandboxID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSandboxesSandboxIDPauseResponse(rsp)
}

// PostSandboxesSandboxIDRenewExpirationWithBodyWithResponse request with arbitrary body returning *PostSandboxesSandboxIDRenewExpirationResponse
func (c *ClientWithResponses) PostSandboxesSandboxIDRenewExpirationWithBodyWithResponse(ctx context.Context, sandboxID SandboxID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSandboxesSandboxIDRenewExpirationResponse, error) {
	rsp, err := c.PostSandboxesSandboxIDRenewExpirationWithBody(ctx, sandboxID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSandboxesSandboxIDRenewExpirationResponse(rsp)
}

func (c *ClientWithResponses) PostSandboxesSandboxIDRenewExpirationWithResponse(ctx context.Context, sandboxID SandboxID, body PostSandboxesSandboxIDRenewExpirationJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSandboxesSandboxIDRenewExpirationResponse, error) {
	rsp, err := c.PostSandboxesSandboxIDRenewExpiration(ctx, sandboxID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSandboxesSandboxIDRenewExpirationResponse(rsp)
}

// PostSandboxesSandboxIDResumeWithResponse request returning *PostSandboxesSandboxIDResumeResponse
func (c *ClientWithResponses) PostSandboxesSandboxIDResumeWithResponse(ctx context.Context, sandboxID SandboxID, reqEditors ...RequestEditorFn) (*PostSandboxesSandboxIDResumeResponse, error) {
	rsp, err := c.PostSandboxesSandboxIDResume(ctx, sandboxID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSandboxesSandboxIDResumeResponse(rsp)
}

// ParseGetSandboxesResponse parses an HTTP response from a GetSandboxesWithResponse call
func ParseGetSandboxesResponse(rsp *http.Response) (*GetSandboxesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSandboxesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListSandboxesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostSandboxesResponse parses an HTTP response from a PostSandboxesWithResponse call
func ParsePostSandboxesResponse(rsp *http.Response) (*PostSandboxesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSandboxesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest CreateSandboxResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteSandboxesSandboxIDResponse parses an HTTP response from a DeleteSandboxesSandboxIDWithResponse call
func ParseDeleteSandboxesSandboxIDResponse(rsp *http.Response) (*DeleteSandboxesSandboxIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteSandboxesSandboxIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetSandboxesSandboxIDResponse parses an HTTP response from a GetSandboxesSandboxIDWithResponse call
func ParseGetSandboxesSandboxIDResponse(rsp *http.Response) (*GetSandboxesSandboxIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSandboxesSandboxIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Sandbox
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetSandboxesSandboxIDEndpointsPortResponse parses an HTTP response from a GetSandboxesSandboxIDEndpointsPortWithResponse call
func ParseGetSandboxesSandboxIDEndpointsPortResponse(rsp *http.Response) (*GetSandboxesSandboxIDEndpointsPortResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSandboxesSandboxIDEndpointsPortResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Endpoint
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostSandboxesSandboxIDPauseResponse parses an HTTP response from a PostSandboxesSandboxIDPauseWithResponse call
func ParsePostSandboxesSandboxIDPauseResponse(rsp *http.Response) (*PostSandboxesSandboxIDPauseResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSandboxesSandboxIDPauseResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostSandboxesSandboxIDRenewExpirationResponse parses an HTTP response from a PostSandboxesSandboxIDRenewExpirationWithResponse call
func ParsePostSandboxesSandboxIDRenewExpirationResponse(rsp *http.Response) (*PostSandboxesSandboxIDRenewExpirationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSandboxesSandboxIDRenewExpirationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RenewSandboxExpirationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostSandboxesSandboxIDResumeResponse parses an HTTP response from a PostSandboxesSandboxIDResumeWithResponse call
func ParsePostSandboxesSandboxIDResumeResponse(rsp *http.Response) (*PostSandboxesSandboxIDResumeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSandboxesSandboxIDResumeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
