// Package egress provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package egress

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// Defines values for NetworkPolicyDefaultAction.
const (
	NetworkPolicyDefaultActionAllow NetworkPolicyDefaultAction = "allow"
	NetworkPolicyDefaultActionDeny  NetworkPolicyDefaultAction = "deny"
)

// Valid indicates whether the value is a known member of the NetworkPolicyDefaultAction enum.
func (e NetworkPolicyDefaultAction) Valid() bool {
	switch e {
	case NetworkPolicyDefaultActionAllow:
		return true
	case NetworkPolicyDefaultActionDeny:
		return true
	default:
		return false
	}
}

// Defines values for NetworkRuleAction.
const (
	NetworkRuleActionAllow NetworkRuleAction = "allow"
	NetworkRuleActionDeny  NetworkRuleAction = "deny"
)

// Valid indicates whether the value is a known member of the NetworkRuleAction enum.
func (e NetworkRuleAction) Valid() bool {
	switch e {
	case NetworkRuleActionAllow:
		return true
	case NetworkRuleActionDeny:
		return true
	default:
		return false
	}
}

// NetworkPolicy Egress network policy matching the sidecar `/policy` request body.
// If `defaultAction` is omitted, the sidecar defaults to "deny"; passing an empty
// object or null results in allow-all behavior at startup.
type NetworkPolicy struct {
	// DefaultAction Default action when no egress rule matches. Defaults to "deny".
	DefaultAction *NetworkPolicyDefaultAction `json:"defaultAction,omitempty"`

	// Egress List of egress rules evaluated in order.
	Egress *[]NetworkRule `json:"egress,omitempty"`
}

// NetworkPolicyDefaultAction Default action when no egress rule matches. Defaults to "deny".
type NetworkPolicyDefaultAction string

// NetworkRule defines model for NetworkRule.
type NetworkRule struct {
	// Action Whether to allow or deny matching targets.
	Action NetworkRuleAction `json:"action"`

	// Target FQDN or wildcard domain (e.g., "example.com", "*.example.com").
	// IP/CIDR not yet supported in the egress MVP.
	Target string `json:"target"`
}

// NetworkRuleAction Whether to allow or deny matching targets.
type NetworkRuleAction string

// PolicyStatusResponse defines model for PolicyStatusResponse.
type PolicyStatusResponse struct {
	// EnforcementMode Egress sidecar enforcement backend mode.
	EnforcementMode *string `json:"enforcementMode,omitempty"`

	// Mode Derived runtime mode for the current policy.
	Mode *string `json:"mode,omitempty"`

	// Policy Egress network policy matching the sidecar `/policy` request body.
	// If `defaultAction` is omitted, the sidecar defaults to "deny"; passing an empty
	// object or null results in allow-all behavior at startup.
	Policy *NetworkPolicy `json:"policy,omitempty"`

	// Reason Optional human-readable reason when the sidecar returns extra context.
	Reason *string `json:"reason,omitempty"`

	// Status Operation status reported by the sidecar.
	Status *string `json:"status,omitempty"`
}

// PatchPolicyJSONBody defines parameters for PatchPolicy.
type PatchPolicyJSONBody = []NetworkRule

// PatchPolicyJSONRequestBody defines body for PatchPolicy for application/json ContentType.
type PatchPolicyJSONRequestBody = PatchPolicyJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetPolicy request
	GetPolicy(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchPolicyWithBody request with any body
	PatchPolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchPolicy(ctx context.Context, body PatchPolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetPolicy(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPolicyRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchPolicyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchPolicyRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchPolicy(ctx context.Context, body PatchPolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchPolicyRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetPolicyRequest generates requests for GetPolicy
func NewGetPolicyRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/policy")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchPolicyRequest calls the generic PatchPolicy builder with application/json body
func NewPatchPolicyRequest(server string, body PatchPolicyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchPolicyRequestWithBody(server, "application/json", bodyReader)
}

// NewPatchPolicyRequestWithBody generates requests for PatchPolicy with any type of body
func NewPatchPolicyRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/policy")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetPolicyWithResponse request
	GetPolicyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetPolicyResponse, error)

	// PatchPolicyWithBodyWithResponse request with any body
	PatchPolicyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchPolicyResponse, error)

	PatchPolicyWithResponse(ctx context.Context, body PatchPolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchPolicyResponse, error)
}

type GetPolicyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PolicyStatusResponse
}

// Status returns HTTPResponse.Status
func (r GetPolicyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPolicyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchPolicyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PolicyStatusResponse
}

// Status returns HTTPResponse.Status
func (r PatchPolicyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchPolicyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetPolicyWithResponse request returning *GetPolicyResponse
func (c *ClientWithResponses) GetPolicyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetPolicyResponse, error) {
	rsp, err := c.GetPolicy(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPolicyResponse(rsp)
}

// PatchPolicyWithBodyWithResponse request with arbitrary body returning *PatchPolicyResponse
func (c *ClientWithResponses) PatchPolicyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchPolicyResponse, error) {
	rsp, err := c.PatchPolicyWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchPolicyResponse(rsp)
}

func (c *ClientWithResponses) PatchPolicyWithResponse(ctx context.Context, body PatchPolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchPolicyResponse, error) {
	rsp, err := c.PatchPolicy(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchPolicyResponse(rsp)
}

// ParseGetPolicyResponse parses an HTTP response from a GetPolicyWithResponse call
func ParseGetPolicyResponse(rsp *http.Response) (*GetPolicyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPolicyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PolicyStatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePatchPolicyResponse parses an HTTP response from a PatchPolicyWithResponse call
func ParsePatchPolicyResponse(rsp *http.Response) (*PatchPolicyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchPolicyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PolicyStatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
